language: minimal
git:
  depth: 1

env:
  global:
    - GH_REF=github.com/Poeschl/Technic-Pack-Repository-Template.git

if: tag IS present

before_install:
  - sudo apt-get update
  - sudo apt-get install -y zip wget

install:
  - chmod +x .scripts/buildPack.sh
  - chmod +x .scripts/deploy.sh

script:
  - .scripts/buildPack.sh

after_success:
  - .scripts/deploy.sh
